### ISSUE TITLE
hello, you don't provide the raw data pkl file, could you updata these file?

### ISSUE THREAD

**Issue by klljf0** [azminewasi/HRGraph#1]
in your raw data folder, there are 2 csv file, not pkl file, could you update them?"

**Comment by azminewasi** [comment]
The pkl file contains the constructed graphs - from the csv files - as mentioned in the paper, we passed these CV/JDs into LLMs using prompts to get the nodes. And edges were JD/CV to corresponding nodes from that CV/JD.

The file size is huge, so uploading it in the repo was a bit problematic from my end - so, we decided to not to add it - also, it can be built very very easily, by simple LLM inference and networkx graph construction. Also, the pkl file doesn't contain any primary data - the main data is the CVs/JDs.

I'll try to add the LLM prompting codes here by 72 hours.

**Update: Information added.**

**Comment by klljf0** [comment]
Thank u
